### ISSUE TITLE
Discuss how we can make this package run in a data driven way

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#101]
@xihang-chen and I were chatting about this on thursday :) 

Two types of analysis
1) hypothesis driven i.e. we know amiodarone > problems with thyroid > levothyroxine or we know dementia drugs cause sickness so people can be prescribed anti sickness.
2) hypothesis generating/exploring: Take a ingredient (or maybe drug class) and run it against every other ingredient possible

Data driven way will need to be thought about 1) there are potentially thousands of ingredients 2) how much time would this take 3) could be use drugutilisation diagnostics to evaluate ingredients and bin ones that have no counts/low counts/route 4) is there a way we can make this a more structured way? so have a inbuilt list of ATC classfication and say run CVD chapter?

Something to discuss at the end of a successful sprint!

**Comment by daniellenewby** [comment]
https://dom-pubs.onlinelibrary.wiley.com/doi/full/10.1111/dom.14982
Data driven example

**Comment by xihang-chen** [comment]
Ed's comment: add some sort of lower bound on the number of people with a particular drug to be included in the analysis. The parameter - minimal sample size reserverd for the users.

**Comment by daniellenewby** [comment]
Also the use of codelistgenerator functions to pull out concepts:
https://darwin-eu.github.io/CodelistGenerator/reference/getATCCodes.html

**Comment by daniellenewby** [comment]
this is not important for the package and is a user problem - have created a repo to do this ssa_Data_Driven
