### ISSUE TITLE
test coverage 

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#119]
devtools::test_coverage()

**Comment by xihang-chen** [comment]
using the current tests and eventually swap out for the omock functions

**Comment by Braventos** [comment]
see current test coverage below:
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/80947940/bdf30ab0-50b6-4c60-96b0-43dffd20912d)

**Comment by xihang-chen** [comment]
ideally 80%

**Comment by xihang-chen** [comment]
a part of #177 now
