### ISSUE TITLE
Consider renaming package

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#12]
As I think the plan is that the package could be used beyond prescriptions, we might not want the p in PSSA as the package becomes for sequence symmetry analysis more generally

If we want to align with other packages, what about calling it something like CohortSymmetry?

**Comment by daniellenewby** [comment]
That is a good point.. this is @xihang-chen's call - maybe CohortSequenceSymmetryAnalysis? CohortSequenceSymmetry?

**Comment by edward-burn** [comment]
If we do change, @xihang-chen here's the process to do it https://www.njtierney.com/post/2017/10/27/change-pkg-name/ Not too painful now, but once something is on cran it becomes much more complicated

@daniellenewby CohortSequenceSymmetryAnalysis is a little long, but it is clear :)

**Comment by xihang-chen** [comment]
I like CohortSequenceSymmetry, concise and avoids acronyms. But we could ask the wider team about their suggestions :) @edward-burn @daniellenewby

**Comment by xihang-chen** [comment]
Rename it to CohortSymmetry
