### ISSUE TITLE
check urls

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#125]
At the moment if I run urlchecker::url_check(), I get 
```
urlchecker::url_check()
✖ Error: README.md:61:6 403: Forbidden
al.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4690514/)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

CRAN will check this and so we need to fix it before submission

**Comment by xihang-chen** [comment]
worst case scenario just remove the url linking to Nicole's paper

**Comment by xihang-chen** [comment]
the url check includes Vignettes etc
