### ISSUE TITLE
Marker/index name not being brought into summarised table in getSequenceRatio when user renames the cohort id

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#160]
I am doing the postive control amidarone (index) with levothyroxine (marker) on the 100K in GOLD 202207. Instantiating was ok and CohortSymmetry::getCohortSequence was ok however when i run this part of the code:

amiodarone_levothyroxin <- CohortSymmetry::getSequenceRatios(cdm = cdm, 
                                                             outcomeTable = "amiodarone_levothyroxine")

This produces the summarized object however the marker name is NA when i would expect it to be levothyroxine. Can we check that the marker name is being brought through please? Tagging @xihang-chen and @nmercadeb 

I checked its because i did this:
cdm[["amiodarone"]] <- cdm[["amiodarone"]] %>%
dplyr::mutate(cohort_definition_id = 1, cohort_name = "Amiodarone") %>%
dplyr::compute()

cdm[["levothyroxine"]] <- cdm[["levothyroxine"]] %>%
dplyr::mutate(cohort_definition_id = 2, cohort_name = "Levothyroxine") %>%
dplyr::compute()

If i dont do this then it works as expected

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/43333cf6-a82f-4ec7-ad92-86ec7f1f5044)

**Comment by nmercadeb** [comment]
hi @daniellenewby  probably what you need is:
if you have only one cohort:
```
cdm[["amiodarone"]] <- cdm[["amiodarone"]] %>%
  newCohortTable(cohortSetRef = tibble(
    cohort_definition_id = 1, cohort_name = "amiodarone"
  ))
```
if you have multiple cohorts that you want to merge into only one cohort:
```
cdm[["amiodarone"]] <- cdm[["amiodarone"]] %>%
  mutate(cohort_definition_id = 1) |>
  compute(name = "amiodarone", temporary = FALSE) |>
  newCohortTable(cohortSetRef = tibble(
    cohort_definition_id = 1, cohort_name = "amiodarone"
  ))
```
PS: it is @catalamarti writing from nuria's account hahha

**Comment by daniellenewby** [comment]
Thank you @catalamarti .. i am not sure i am doing this correctly but..

cdm[["test_drugs"]] <- union_all(cdm[["dorzolamide"]] %>% dplyr::mutate(cohort_definition_id = 1, cohort_name = "dorzolamide"),
                                 cdm[["eszopiclone"]] %>% dplyr::mutate(cohort_definition_id = 2, cohort_name = "eszopiclone"),
                                 cdm[["fexofenadine"]] %>% dplyr::mutate(cohort_definition_id = 3, cohort_name = "fexofenadine"),
                                 cdm[["goserelin"]] %>% dplyr::mutate(cohort_definition_id = 4, cohort_name = "goserelin"),
                                 cdm[["simvastatin"]] %>% dplyr::mutate(cohort_definition_id = 5, cohort_name = "simvastatin"),
                                 cdm[["aspirin"]] %>% dplyr::mutate(cohort_definition_id = 6, cohort_name = "aspirin"),
                                 cdm[["heparin"]] %>% dplyr::mutate(cohort_definition_id = 7, cohort_name = "heparin"),
                                 cdm[["ibuprofen"]] %>% dplyr::mutate(cohort_definition_id = 8, cohort_name = "ibuprofen"),
                                 cdm[["indomethacin"]] %>% dplyr::mutate(cohort_definition_id = 9, cohort_name = "indomethacin"),
                                 cdm[["prednisolone"]] %>% dplyr::mutate(cohort_definition_id = 10, cohort_name = "prednisolone")) %>%
  dplyr::compute(name = "test_drugs" , temporary = FALSE) %>%
  newCohortTable(cohortSetRef = tibble(
    cohort_definition_id = c(1:10), 
    cohort_name = c(
      "dorzolamide" ,
      "eszopiclone" ,
      "fexofenadine" ,
      "goserelin" ,
      "simvastatin" ,
      "aspirin" ,
      "heparin" ,
      "ibuprofen" ,
      "indomethacin" ,
      "prednisolone" )))

Here is the error message:
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/53b08048-603d-4638-a1a6-e6872155e146)

For cohortsymmetry i want to be able to have a cohort with multiple cohort ids so it runs against all these index drugs against my marker (gi bleed/ulcer). So then after i have created this table i can just do this:

cdm <- CohortSymmetry::getCohortSequence(cdm = cdm,
                                         name = "gi_benchmarkers",
                                         dateRange = c(starting_date, ending_date),
                                         indexTable = "test_drugs",
                                         markerTable = "upper_gi_ulcer",
                                         daysPriorObservation = 365,
                                         washoutWindow = 365,
                                         indexMarkerGap = NULL, # if null it uses the second argument of the combinationWindow
                                         combinationWindow = c(0, 365))

upper_gi_ulcer_benchmarkers <- CohortSymmetry::getSequenceRatios(cdm = cdm, outcomeTable = "gi_benchmarkers")
and i will get a result per index i.e. 10 rows

**Comment by catalamarti** [comment]
This should work:
```
cdm[["test_drugs"]] <- union_all(
  cdm[["dorzolamide"]] %>% dplyr::mutate(cohort_definition_id = 1),
  cdm[["eszopiclone"]] %>% dplyr::mutate(cohort_definition_id = 2),
  cdm[["fexofenadine"]] %>% dplyr::mutate(cohort_definition_id = 3),
  cdm[["goserelin"]] %>% dplyr::mutate(cohort_definition_id = 4),
  cdm[["simvastatin"]] %>% dplyr::mutate(cohort_definition_id = 5),
  cdm[["aspirin"]] %>% dplyr::mutate(cohort_definition_id = 6),
  cdm[["heparin"]] %>% dplyr::mutate(cohort_definition_id = 7),
  cdm[["ibuprofen"]] %>% dplyr::mutate(cohort_definition_id = 8),
  cdm[["indomethacin"]] %>% dplyr::mutate(cohort_definition_id = 9),
  cdm[["prednisolone"]] %>% dplyr::mutate(cohort_definition_id = 10)
) %>%
  dplyr::compute(name = "test_drugs" , temporary = FALSE) %>%
  newCohortTable(cohortSetRef = tibble(
    cohort_definition_id = c(1:10),
    cohort_name = c(
      "dorzolamide", "eszopiclone", "fexofenadine", "goserelin", "simvastatin",
      "aspirin", "heparin", "ibuprofen", "indomethacin", "prednisolone"
    )
  ))
```

this should also work:
```
cdm <- bind(
  cdm$dorzolamide, cdm$eszopiclone, cdm$fexofenadine, cdm$goserelin, cdm$simvastatin,
  cdm$aspirin, cdm$heparin, cdm$ibuprofen, cdm$indomethacin, cdm$prednisolone,
  name = "test_drugs"
)
```

Although I dont understand why they are in different tables and not created together.

@daniellenewby

**Comment by catalamarti** [comment]
Then probably what you need is the bind function

**Comment by daniellenewby** [comment]
great will have a go and i am sure you will know about it if it doesnt work :) thanks!

**Comment by daniellenewby** [comment]
bind function using omopgenerics works :)
