### ISSUE TITLE
Consider renaming outcomeTable in getSequenceRatios 

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#162]
@xihang-chen probably could be called something that made it clearer this is expected to be the table that is produced by getCohortSequence 

https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/5adbd4b6b53ad3bd01c6403f7a8dbc241f87a44f/R/getSequenceRatios.R#L36

**Comment by catalamarti** [comment]
If it creates a cohort, should we use the typical structure:
```
cdm <- generateSequenceCohortSet(cdm, name, ...)
```
