### ISSUE TITLE
table functions

### ISSUE THREAD

**Issue by nmercadeb** [oxford-pharmacoepi/CohortSymmetry#164]
- [x] formatSequenceSymmetry to tableSequenceRatios
- [x] result_type column to "sequence_ratio"
- [x] eliminate tidy function
- [ ] reexport tidy from visOmopResults 
- [ ] add settings to summarised result 

@edward-burn @catalamarti are these tasks correct after today's meeting?

**Comment by edward-burn** [comment]
@nmercadeb yes please!
