### ISSUE TITLE
 summariseSequenceRatio: consider renaming restriction argument

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#189]
@xihang-chen @daniellenewby not sure if it is possible, but changing the name of the argument "restriction" to something a little more descriptive might be helpful

**Comment by xihang-chen** [comment]
nsrMovingWindow?

**Comment by daniellenewby** [comment]
MovingAverage

**Comment by catalamarti** [comment]
```
averagePeriod
averageDays
```
I would not use the word window

**Comment by xihang-chen** [comment]
movingAverageRestriction? @edward-burn @daniellenewby @catalamarti kind of combination of both ideas.
