### ISSUE TITLE
getCohortSequenceSet() is taking longer than expected

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#191]
Currently using pharamatrics but it has been taking about a day now.

**Comment by catalamarti** [comment]
Why do we have to tally here?
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L173-L182

**Comment by catalamarti** [comment]
we should add a compute before each `recordCohortAttrition`

**Comment by catalamarti** [comment]
```
... |>
  dplyr::compute(name = name, temporary = FALSE) |>
  omopgenerics::recordCohortAttrition(...)
```
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L197
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L202
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L210
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L218

**Comment by KimLopezGuell** [comment]
Second this, I am working with synthea and it is taking already 6+ hours for one index cohort and two marker cohorts

**Comment by daniellenewby** [comment]
Spoke to Hez this is still a problem - even when i terminate after trying to run generateSequenceCohortSet its still generating temp tables. @xihang-chen removed alot of the perm tables to temp but this has not made this step quicker. @catalamarti . There is something lurking in this code that is 1) creating lots of tables and eating up memory on the server 2) carries on even after a user has terminated and only Hez can stop it 3) its really slow

**Comment by xihang-chen** [comment]
Error found by Marti: left_join() https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/main/R/generateSequenceCohortSet.R#L300
