### ISSUE TITLE
Incompatibility between generateSequenceCohortSet() and databases with multiple observation periods per person

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#195]
I was trying to use the pharmatrics database (100k) and tried to observe if there is a signal between CCB and Diuretics.
I initiated ccb and diuretics cohort sets like so:

```
cdm <- DrugUtilisation::generateAtcCohortSet(cdm = cdm,
                                             name = "ccb",
                                             atcName = "CALCIUM CHANNEL BLOCKERS",
                                             level = c("ATC 2nd"))

cdm <- DrugUtilisation::generateAtcCohortSet(cdm = cdm,
                                             name = "diuretics",
                                             atcName = "diuretics",
                                             level = c("ATC 2nd"))
```

but when I tried 
```
cdm <- CohortSymmetry::generateSequenceCohortSet(cdm = cdm,
                                                 indexTable = "ccb",
                                                 markerTable = "diuretics",
                                                 name = "ccb_diuretics")
```
it threw an error:
```
Error in `validateGeneratedCohortSet()`:
! 37 observations outside observation period.
```
which stemmed from omopgenerics::newCohortTable() 
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/662afe22b4a12423fd071d98a4ef1df3b82eb4fd/R/generateSequenceCohortSet.R#L187C3-L189C60

I checked why it was throwing this error, it seems it is because per person the pharmatrics allowed more than one observation period, which seems incompatible with omopgenerics.

@catalamarti @edward-burn @daniellenewby should we allow CohortSymmetry to have multiple obs periods per person? Or should we make changes to omopgenerics?

I think if we would like to change CohortSymmetry a bit to counter this issue we would need the first episode in the observation period but then should we pick the first episode in the first observation period?

**Comment by edward-burn** [comment]
@xihang-chen in omop database people can have more than one observation period, they just can't be ovelapping

**Comment by edward-burn** [comment]
So yes we'll have to account for this and add some tests for these cases

**Comment by xihang-chen** [comment]
@catalamarti @edward-burn am I right in thinking if I have a cohort that I want to insert using omopgenerics::newCohortTable() such that the cohort_start_date lies in an observation period and cohort_end_date lies in another observation period for the that person, that is not allowed?

e.g., for subject_id = 1 this person has two observation periods:
1. 1st Jan 2020 to 1st Feb 2020
2. 3rd Feb 2020 to 7th March 2020

Say if I want a cohort containing this subject_id = 1 with cohort_start_date 2nd Jan 2020 and cohort_end_date 1st March 2020, omopgenerics::newCohortTable() would throw an error, right?

**Comment by catalamarti** [comment]
It should trow an error yes, but it would be a nice test to add @xihang-chen

**Comment by xihang-chen** [comment]
thanks all! I think in that case we would also need to make sure both cohort_start_date and cohort_end_date fall in the same observation period for generateSequenceCohortSet()
