### ISSUE TITLE
add more arguments to getCohortSequence function 

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#25]
add cohortDateRange, eventWashout and priorObservation  (and possibly restrictToFirstEverSequence)

**Comment by Braventos** [comment]
As discussed with @edward-burn  and @xihang-chen, add sequenceWashout and restrictToFirstEverSequence (or firstEver). 

- If restrictToFirstEverSequence=TRUE: Capture first-ever sequence in patient's history
- If restrictToFirstEverSequence=FALSE: Capture first-ever sequence in the study period

Once the first sequence is identified then assess its elegibility for the analysis.

**Comment by xihang-chen** [comment]
closing it as we will stick to the literature way for now. e.g., Tsiropoulos 2009, adding more arguments using Hendrix 2024
