### ISSUE TITLE
Upper case column names

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/CohortSymmetry#262]
If we turn this into error in omopgenerics, it says we break CohortSymmetry
@xihang-chen would be nice to check when uppercase columns are used and change that
<img width="703" alt="Screenshot 2024-08-14 at 21 42 19" src="https://github.com/user-attachments/assets/5d2d4348-5968-4903-b3cd-c9c7adc4003f">

**Comment by xihang-chen** [comment]
hey @catalamarti does it only apply to tables that are being inserted into the cdm reference? or does it apply to other dataframes that are being created along the way like summarise results objects? :)
