### ISSUE TITLE
consider adding attrition 

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#35]
Helpful example: https://github.com/darwin-eu-dev/IncidencePrevalence/blob/main/R/generateDenominatorCohortSet.R

**Comment by edward-burn** [comment]
@xihang-chen fyi omopgenerics is providing a attrition method we can use to help with this

**Comment by xihang-chen** [comment]
add attritions to see how many people fall off during getCohortSeuqnce()
