### ISSUE TITLE
add shiny for package results of CohortSymmetry

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#60]
For outputs from package it would be great to have a shiny see here for examples:

https://github.com/oxford-pharmacoepi/EHDENCancerSurvivalStudyShiny
https://github.com/oxford-pharmacoepi/EHDENCancerIncSurvCovid
https://github.com/oxford-pharmacoepi/EHDENCancerExtrapolationStudyShiny

**Comment by xihang-chen** [comment]
Closing this as I think OmopViewer can handle this now
