### ISSUE TITLE
Add 95% confidence intervals for adjusted sequence ratio

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#62]
For the crude sequence ratio's confidence intervals can be calculated however we also need confidence intervals for the adjusted sequence ratio. Other studies do report CI's so we need to calculate and include them too. Examples below

https://www.sciencedirect.com/science/article/pii/S1525861021006010
https://link.springer.com/article/10.1007/s40264-018-0638-2

And here it is for bootstrapping in original code: https://github.com/tystan/seqsym/blob/main/R/boot_ci.R we need to update it using: https://pubmed.ncbi.nlm.nih.gov/36448210/

**Comment by xihang-chen** [comment]
think it works now, closing it as a result. At the end I did lower_ci_csr dividing by nsr and vice versa for upper_ci_csr.
