### ISSUE TITLE
update cohortSet information when combining drug ingredients together

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#67]
Example i am looking at 3 drugs for dementia that i instantiate as 3 ingredients - each with a cohort_name that when i write cohortSet it gives me back these three names. However for PSSA we sometimes want to combine ingredients together as well as study at the ingredient level. So i am able to combine all three drugs into one cohort however the cohortSet or getCohortNames from patientprofiles does not update. This is important as the results only give marker or index drug ID's and we need for ease to pull out the cohort names using existing packages i.e. patient profiles

**Comment by edward-burn** [comment]
@xihang-chen fyi omopgenerics is going to provide a bind method that might be helpful for this

**Comment by daniellenewby** [comment]
used the bind function and works
