### ISSUE TITLE
GetParticipants for cohort symmetry

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#68]
We may need to characterise the patients taking the medications tested using cohort symmetry. So a getParticipants might be useful to pull out those people who are taking both drugs and also highlighting those who take the index first or marker first respectively

**Comment by edward-burn** [comment]
@xihang-chen for this we can implement the participants method from omopgenerics (fyi @catalamarti)

**Comment by daniellenewby** [comment]
closing this as not needed as other packages can be used
