### ISSUE TITLE
CohortSymmetry::getCohortSequence eating up Rstudio memory and causing rstudio to crash

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#74]
Bug: when running lots of cohorts and CohortSymmetry::getCohortSequence arguments it eats up the internal R memory causing the session to crash - spoke to @catalamarti about this and will have to look at the getCohortSequence bits of this to see if something is being collected and taking up memory :) been trying one cohort at a time and still not working. Updated to new version of cohortsymmetry and still not working.

**Comment by xihang-chen** [comment]
the problem is the way of me defining the temp (list) high cohort_definition_id means too large temp list, causing the crash

**Comment by daniellenewby** [comment]
This still is eating up memory so not sure it is sorted :( 

**if i set this to 17 the memory gets large but works fine if i set it to 1**
cdm[["antipsych_lithium_com"]] <- cdm[["antipsych_lithium"]] %>%
  dplyr::mutate(cohort_definition_id = 17, cohort_name = "Antipsychotics Lithium") %>%
  dplyr::compute()

**this section below is eating up memory**
cdm <- CohortSymmetry::getCohortSequence(cdm = cdm,
                                         name = "ache_inhib_antipsych_lithium",
                                         dateRange = c(starting_date, ending_date),
                                         indexTable = "ache_inhibitors_com",
                                         markerTable = "antipsych_lithium_com",
                                         daysPriorObservation = 365,
                                         indexWashout = 365,
                                         markerWashout = 365,
                                         timeGap = 365)


ache_inhib_antipsych_lithium <- CohortSymmetry::getSequenceRatios(cdm = cdm, outcomeTable = "ache_inhib_antipsych_lithium") %>% 
  mutate(Analysis = "Test Drugs",         
         Index_name = cdm[["ache_inhibitors_com"]] %>%  distinct(cohort_name) %>% 
           pull(),
         Marker_name = cdm[["antipsych_lithium_com"]] %>%  distinct(cohort_name) %>% 
           pull()
  ) %>% 
  readr::write_csv(file = paste0(here::here(output.folder),"/", cdm_name(cdm) ,"_" , cdm[["ache_inhibitors_com"]] %>%  distinct(cohort_name) %>% 
                                   pull() , "_" , cdm[["antipsych_lithium_com"]] %>%  distinct(cohort_name) %>% 
                                   pull() ,
                                 
                                 ".csv"))

**Comment by daniellenewby** [comment]
restarting R studio and session and being sensible meant this is now working
