### ISSUE TITLE
plotting functions for CohortSymmetry

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/CohortSymmetry#75]
Like with other packages (incidenceprevalence, cohortsurvival etc) it would be good to develop code to plot things from outputs from CohortSymmetry. Two types of plots might be required by a user. 

**1.  Histogram of drug use for the marker and index sequences** This would have to be pulled out and stored out so a user can download the aggreated data to make this plot - so would be able to use this function with or without access to the a server
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/e797b321-4b46-4510-9e55-6fe9505ee055)

**2. Plot showing the results of aSR for different drug/condition pairs** This can be generated from output from results
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/ba441df1-cdc0-4bd8-8f22-063ba54eb5b0)

`library(dplyr)
library(ggplot2)

filepath_pssa <- "xxxx"

results <-list.files(filepath_pssa, full.names = TRUE,
                     recursive = TRUE,
                     include.dirs = TRUE,
                     pattern = ".zip")

#unzip data
for (i in (1:length(results))) {
  utils::unzip(zipfile = results[[i]],
               exdir = filepath_pssa)
}

#grab the results from the folders
results <- list.files(
  path = filepath_pssa,
  pattern = ".csv",
  full.names = TRUE,
  recursive = TRUE,
  include.dirs = TRUE
)

pssa_estimates <- list()
for(i in seq_along(results)){
  pssa_estimates[[i]]<-readr::read_csv(results[[i]],
                                           show_col_types = FALSE)
}
pssa_estimates <- dplyr::bind_rows(pssa_estimates) %>% 
  mutate(drug_pairs = paste(Index_name, Marker_name, sep = " > "))

figure <- pssa_estimates %>% 
  filter(asr < 5) %>% 
  filter(Marker_name != "Antipsychotics Lithium") %>% 
  filter(Marker_name != "Diuretics") %>% 
  filter(Marker_name != "Calcium Channel Blockers") %>% 
  filter(Marker_name != "Bladder anticholinergics") %>% 
  filter(Marker_name != "Beta Blockers") %>% 
  filter(Marker_name != "ARBs") %>% 
  filter(Marker_name != "ACE Inhibitors") %>% 
  filter(Marker_name != "Allopurinol") %>% 
ggplot(aes(x = asr, y = drug_pairs)) +
  geom_vline(xintercept = 1, linetype = "dotted", color = "black") +
  geom_errorbarh(aes(xmin = lowerASR_CI, xmax = upperASR_CI, colour = Analysis), height = 0, size = 1) +
  geom_point(aes(colour = Analysis, fill = Analysis), size = 2, shape = 21, colour = "black") +  # Add outline to dots
  labs(x = "aSR", y = "Drug Pairs") +
  guides(colour = FALSE) +
  theme_bw() +
  scale_x_continuous(limits = c(0, 4))

figure

readr::write_csv(pssa_estimates, file = paste0(filepath_pssa ,"results.csv")) 

`

**Comment by daniellenewby** [comment]
I think we need a another plot to have a look at the prescription trends over time for each drug like this - this should be called plotTemporalTrend.

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/46cdb14d-bb25-4227-b3c4-f7ed9da7a7e9)

https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-14-66

Pulled this from the original package if needed
globalVariables(c(
  "ym", "n", "drug", "patid"
))

#' Plot drug incident use by month in study
#'
#' @author Ty Stanford, Nicole Pratt
#' @description Plot drug incident use by month in study similar to Fig. 1 in Pratt et al. (2014)
#' @param dat_rand a dataset generated from \code{mk_dat_rand}
#' @param a_and_b logical, FALSE will produce plot for all prescribed drugs, TRUE will only plot
#' prescriptions where both drugs A and B have been provided to the same person
#' @return A ggplot object (a plot)
#' @export
#' @examples
#' this_dat <- mk_dat_rand(1000, 50, 50, 5, seed_ = 1234)
#' plot_incident_use(this_dat)


plot_incident_use <- function(dat_rand, a_and_b = FALSE, patid = "patid", dateA = "dateA", dateB = "dateB") {

  check_cols(dat_rand, c(patid, dateA, dateB))

  cnms <- colnames(dat_rand)
  cnms[cnms == patid] <- "patid"
  cnms[cnms == dateA] <- "dateA"
  cnms[cnms == dateB] <- "dateB"
  colnames(dat_rand) <- cnms

  options(warn = 2) # make warnings errors, to be caught
  if (!("Date" %in% class(dat_rand[["dateA"]]))) {
    d_convert <- try( {as_date(dat_rand[["dateA"]])} )
    if (class(d_convert) == "try-error") stop(
      "Column ", dateA,
      " is not a date class and threw warning(s)/error(s) when niavely converting"
    )
    dat_rand[["dateB"]] <- d_convert
  }
  if (!("Date" %in% class(dat_rand[["dateB"]]))) {
    d_convert <- try( {as_date(dat_rand[["dateB"]])} )
    if (class(d_convert) == "try-error") stop(
      "Column ", dateB,
      " is not a date class and threw warning(s)/error(s) when niavely converting"
    )
    dat_rand[["dateB"]] <- d_convert
  }
  options(warn = 0) # make warnings warnings again


  if (a_and_b) {
    dat_rand <-
      dat_rand %>%
      dplyr::filter(!is.na(dateA) & !is.na(dateB))
  }

  dat_rand <-
    dat_rand %>%
    select(patid, dateA, dateB)

  piu_dat <-
    dat_rand %>%
    gather(key = "drug", value = "date", -patid) %>%
    dplyr::filter(!is.na(date)) %>% # only required if a_and_b == FALSE
    mutate(
      drug = gsub("date", "", drug),
      ym = paste0(year(date), "-", sprintf("%02.0f", month(date)))
    ) %>%
    group_by(drug, ym) %>%
    summarise(n = n()) %>%
    ungroup()

  max_indic <- piu_dat %>% pull(n) %>% max(.)

  piu <-
    piu_dat %>%
    ggplot(aes(x = ym, y = n, colour = drug, group = drug)) +
    geom_line() +
    labs(y = "Incident use", x = "Year-Month", colour = "Drug") +
    theme_min("grey90") +
    theme(axis.text.x = element_text(angle = 270)) +
    ylim(c(0, max_indic))

  return(piu)

}

**Comment by daniellenewby** [comment]
> `plotSequenceRatio` `plotTemporalTrend`

See previous comment `plotTemporalTrend` is more suited to plotting the temporal trends so not sure this is the right name.  For the symmetry plots (the first example i showed) the name needs to be plotTemporalSymmetry or something like that :)

**Comment by daniellenewby** [comment]
another example for plotting the symmetry of the drugs 

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/69154055-f0af-4c45-829f-fd9c46cd0eb6)

https://dom-pubs.onlinelibrary.wiley.com/doi/full/10.1111/dom.14982

**Comment by daniellenewby** [comment]
@KimLopezGuell here is the figure i am talking about
![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/16097637/3a0f76bf-0446-4474-a00a-4128a568f7cc)
from https://dom-pubs.onlinelibrary.wiley.com/doi/full/10.1111/dom.14982

**Comment by KimLopezGuell** [comment]
@daniellenewby @xihang-chen 
This is the first draft of the sequenceRatio plot:

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/99121045/08fab4eb-6f9c-4933-b061-22bc6829186c)

Before I push any commit, I have a couple of questions:
- Right now there are many variables (the ones in the additional column) that one can choose for different analysis tuning before the plot, but as far as I can see only one value is allowed (i.e. the analyses do not loop through two different combination windows). Therefore I am not expecting results for different values of any of those variables. Will this be a feature in the future? I can build in a facet_wrap in the plot that stratifies by as many different values of any of those variables as there may be, but right now I don't think it's necessary.
- As per usual, the labs, title, ids plotted and colours can be chosen. Tell me if anything else would be nice.

**Comment by KimLopezGuell** [comment]
Regarding the first point, I manually created four results from summariseSequenceRatio() and merged them into one big tibble to feed as input to the plotSequenceRatio() function I am developing. The plot function now sees that some of these additional variables have different values and plots them in a facet wrap like this:

![image](https://github.com/oxford-pharmacoepi/CohortSymmetry/assets/99121045/e2cbc500-1cab-4a5b-9271-2ee96893d67d)

Is this something helpful? If not I can not include it. Also, the facet wrap names are very long, but if we don't put them like this I am afraid it's not clear what variables we are plotting :( 
Also, I guess index_marker_gap does not include additional information if we have combination window, so we can get rid of it @xihang-chen ?

**Comment by daniellenewby** [comment]
> @daniellenewby @xihang-chen This is the first draft of the sequenceRatio plot:
> 
> ![image](https://private-user-images.githubusercontent.com/99121045/310708131-08fab4eb-6f9c-4933-b061-22bc6829186c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjI5NDgsIm5iZiI6MTcwOTgyMjY0OCwicGF0aCI6Ii85OTEyMTA0NS8zMTA3MDgxMzEtMDhmYWI0ZWItNmY5Yy00OTMzLWIwNjEtMjJiYzY4MjkxODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE0NDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYWYyNWE4ZDg0MDdkNjhhYjVmNmI2ZDk4YjBmNGJlODk1ZWI4YmY3MTU2YjI2MzVhNTEyNTM1ZDAwMjg0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o05RdzWGtOYZsNTF3HeRxs6NcR5wo6l13ZIDq_-28JY)
> 
> Before I push any commit, I have a couple of questions:
> 
> * Right now there are many variables (the ones in the additional column) that one can choose for different analysis tuning before the plot, but as far as I can see only one value is allowed (i.e. the analyses do not loop through two different combination windows). Therefore I am not expecting results for different values of any of those variables. Will this be a feature in the future? I can build in a facet_wrap in the plot that stratifies by as many different values of any of those variables as there may be, but right now I don't think it's necessary.
> * As per usual, the labs, title, ids plotted and colours can be chosen. Tell me if anything else would be nice.

Hey @KimLopezGuell this looks amazing!!! Yeah i think for now we can leave it and add in the strata by different settings as i am not sure if this is implemented yet well not for the initial release :). Would it be possible to have an option to plot just the adjusted and not the crude? I like having both in there but not sure others would want to keep the crude in so having the flexibility might be nice :) I think what you have done in the second plot (with the facetting is super nice) Can you check with @xihang-chen about your other question as he would be better to answer it :)

**Comment by xihang-chen** [comment]
> Regarding the first point, I manually created four results from summariseSequenceRatio() and merged them into one big tibble to feed as input to the plotSequenceRatio() function I am developing. The plot function now sees that some of these additional variables have different values and plots them in a facet wrap like this:
> 
> ![image](https://private-user-images.githubusercontent.com/99121045/310744587-e2cbc500-1cab-4a5b-9271-2ee96893d67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjQ0MjEsIm5iZiI6MTcwOTgyNDEyMSwicGF0aCI6Ii85OTEyMTA0NS8zMTA3NDQ1ODctZTJjYmM1MDAtMWNhYi00YTViLTkyNzEtMmVlOTY4OTNkNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE1MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZmZmMjY3ZjUyNzhlNWQ1OGI2YzcwYWI1MGZkMjdmZWUzZGJmYTVhZDg5MDE5YTBjOTA5ZGE5NDRhOGI5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOwK0kCzNnt5HHQbDZoIAZfB8BNmxUEQmM5OlqTZHI0)
> 
> Is this something helpful? If not I can not include it. Also, the facet wrap names are very long, but if we don't put them like this I am afraid it's not clear what variables we are plotting :( Also, I guess index_marker_gap does not include additional information if we have combination window, so we can get rid of it @xihang-chen ?

Hey @KimLopezGuell Great work thank you so much!! Looks really nice!! 

I think we would need to include index_marker_gap. Although it is dependant on combinationWindow, index_marker_gap would in theory give more information than combination_window. e.g., the users could say indexMarkerGap = 7 but combinationWindow = c(0,90). (Essentially indexMarkerGap is an integer that is less than or equal to combinationWindow[[2]].)

But yes currently it only supports one value but in the near future hopefully we would have more than one value for an argument, e.g., washout = c(0, 90).

I don't really have a preference as to whether we should keep the facet_wrap in for now. I think either looks nice!

**Comment by KimLopezGuell** [comment]
The pull request #201 now also has the function plotSequenceRatio() with the option to only plot adjusted ratio added. I have left the facetting option because if all those variables (like right now) only have one value, the facetting is automatically not done. But in the future, with maybe loop options, or with strata functionality, the facetting will already be built.
I have also kept index_marker_gap :).
