### ISSUE TITLE
Testing with OMOPMockR

### ISSUE THREAD

**Issue by xihang-chen** [oxford-pharmacoepi/CohortSymmetry#79]
Transforming tests and examples using OMOPMockR as opposed to using mockDrugUtilisation or mockPatientProfiles.

Especailly testing CEI, blackOutPeriod and combineIndex and combineMarker in getCohortSequence() function.

**Comment by daniellenewby** [comment]
We also need OMOPMockR to have functionality to test prescrbing trends over time with this package. So increasing prescriptions over time, uniform trends, decreased trend over time etc
