### ISSUE TITLE
Try and use permanent tables throughout

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#83]
For most packages we're trying to use permanent tables thoughout as temp tables can be a bit inconsistent across dbms. For intermediate tables we need to make sure to drop them when no longer needed (and you should be able to test than none of these are left over)

**Comment by xihang-chen** [comment]
i think generateCohortSequenceSet() is more or less okay for this issue. summariseSequenceRatio() is probably the only one left to consider.
